name: Coverage check with jest-coverage-guard

on:
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout test repository success example branch
      uses: actions/checkout@v2
      with:
        repository: vitaliyshvarz/vue_coverage_test_app
        ref: success_example
        path: vue_coverage_test_app

    - name: Set origin as test repo
      run: |
        cd vue_coverage_test_app
        git remote -v
        git fetch
        git checkout success_example
        git pull origin success_example
        git log --walk-reflogs success_example
        git log --grep=success_example


        npm install

        rm -rf node_modules/jest-coverage-guard/src
        cp -r ../src node_modules/jest-coverage-guard/src
        
        npm run test:unit
      env:
        TESTING_SUCCESS_GUARD_IN_GITHUB: true

    - name: Checkout test repository failure example branch
      uses: actions/checkout@v2
      with:
        repository: vitaliyshvarz/vue_coverage_test_app
        ref: fail_example
        path: vue_coverage_test_app
  
    - name: Set origin as test repo
      run: |
        cd vue_coverage_test_app
        git remote -v
        git log --grep=fail-example

    - name: Install dependencies in test repo
      run: cd vue_coverage_test_app && npm install

    - name: Copy src folder to test app node_modules
      run: |
        rm -rf vue_coverage_test_app/node_modules/jest-coverage-guard/src
        cp -r src vue_coverage_test_app/node_modules/jest-coverage-guard/src
    - name: Run tests in test app
      run: cd vue_coverage_test_app && npm run test:unit
      env:
        APP_ROOT_PATH: ./
        TESTING_FAILURE_GUARD_IN_GITHUB: true