name: Coverage check with jest-coverage-guard

on:
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies in test app
      run: cd test-app && npm install

    - name: Copy src folder to test app node_modules
      run: |
        rm -rf test-app/node_modules/jest-coverage-guard/src
        cp -r src test-app/node_modules/jest-coverage-guard/src
    - name: Run tests in test app
      run: cd test-app && npm run test:unit
      env:
        APP_ROOT_PATH: ./